### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by cthoyt** [ndexbio/ndex-python#2]
```
Collecting ndex
  Using cached ndex-3.0.11.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/n1/h1c266qj2jq8kfdzfxj53pzw0000gn/T/pip-build-p6abuec2/ndex/setup.py", line 16, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/n1/h1c266qj2jq8kfdzfxj53pzw0000gn/T/pip-build-p6abuec2/ndex/README.md'
```

I think you need to add a `MANIFEST.in` file (try `pip install check-manifest`, run `check-manifest` in the directory and check its suggestions) and also add `include_package_data=True` to the kwargs of `setuptools.setup`

Originally posted in: https://github.com/ndexbio/ndex-python-client/issues/3

**Comment by bgyori** [comment]
Sorry, I accidentally posted to the wrong repo, what I posted was: I also just ran into this problem but only on Python 3. Installation on Python 2 works fine.

**Comment by cthoyt** [comment]
It's not usually obvious how a given package is uploaded to PyPI (usually with the built-in `distutils`, or more preferred `twine`). So I have an idea on why this might be the case:

`setup.cfg` doesn't state that this code is universal for python2/python3 so perhaps it was just a mistake in manual addition of the extra files. This [stackoverflow answer](http://stackoverflow.com/questions/24727709/i-dont-understand-python-manifest-in) has a good explanation of which files get copied automatically without further information from a `MANIFEST.in` file (all python modules, `README.txt`, and `test/test*.py`) which leads me to believe `README.md` might not make it by default

**Comment by jingjingbic** [comment]
I have uploaded a new package (3.0.11.19). Could you try it?

**Comment by rpillich** [comment]
Just to be in the loop... is this the same build that you pushed to ndex-dev last friday?
ThanksR


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by jingjingbic** [comment]
Yes.

**Comment by bgyori** [comment]
The install works for me now, thanks!

**Comment by cthoyt** [comment]
Works for me too!
